ACCESS_TOKEN_TTL_MINUTES = 15
REFRESH_TOKEN_TTL_DAYS = 30
JWT_ALGORITHM = "HS256"
R2_UPLOAD_SIGNED_URL_TTL_SECONDS = 300
R2_DOWNLOAD_SIGNED_URL_TTL_SECONDS = 300
APP_TIMEZONE = "Asia/Seoul"
DB_TIMEZONE = "UTC"

# Phase-1 fixed policy values that can be shared by later tickets.
INVITE_CODE_TTL_SECONDS = 600
MAX_CHILDREN_PER_PARENT = 5
MAX_PARENTS_PER_CHILD = 2
INVITE_VERIFY_RATE_LIMIT_MAX_ATTEMPTS = 5
INVITE_VERIFY_RATE_LIMIT_WINDOW_SECONDS = 600
INVITE_CONSUME_RATE_LIMIT_MAX_ATTEMPTS = 5
INVITE_CONSUME_RATE_LIMIT_WINDOW_SECONDS = 600
PASSWORD_MIN_LENGTH = 8

SYNC_EVENTS_BATCH_MAX_SIZE = 100
SYNC_EVENT_SCHEMA_VERSION = 1
SYNC_DEVICE_ID_MAX_LENGTH = 128
SYNC_IDEMPOTENCY_KEY_MAX_LENGTH = 128
SYNC_EVENT_STRING_MAX_LENGTH = 128

SYNC_EVENT_TYPE_TODAY_ATTEMPT_SAVED = "TODAY_ATTEMPT_SAVED"
SYNC_EVENT_TYPE_MOCK_EXAM_ATTEMPT_SAVED = "MOCK_EXAM_ATTEMPT_SAVED"
SYNC_EVENT_TYPES = (
    SYNC_EVENT_TYPE_TODAY_ATTEMPT_SAVED,
    SYNC_EVENT_TYPE_MOCK_EXAM_ATTEMPT_SAVED,
)

WRONG_REASON_TAG_DB_VALUES = (
    "VOCAB",
    "EVIDENCE",
    "INFERENCE",
    "CARELESS",
    "TIME",
)

CONTENT_IDENTIFIER_MAX_LENGTH = 128
CONTENT_OBJECT_KEY_MAX_LENGTH = 512
CONTENT_TITLE_MAX_LENGTH = 255
CONTENT_REVISION_CODE_MAX_LENGTH = 32
CONTENT_QUESTION_CODE_MAX_LENGTH = 128
CONTENT_TEXT_MAX_LENGTH = 20000
CONTENT_LIST_DEFAULT_PAGE_SIZE = 20
CONTENT_LIST_MAX_PAGE_SIZE = 100

CONTENT_ASSET_ALLOWED_MIME_TYPES = (
    "application/json",
    "application/pdf",
    "audio/mpeg",
    "audio/mp4",
    "audio/wav",
    "audio/webm",
    "image/jpeg",
    "image/png",
    "text/plain",
)

MOCK_EXAM_EXTERNAL_ID_MAX_LENGTH = 128
MOCK_EXAM_SLUG_MAX_LENGTH = 128
MOCK_EXAM_TITLE_MAX_LENGTH = 255
MOCK_EXAM_INSTRUCTIONS_MAX_LENGTH = 20000
MOCK_EXAM_TRACEABILITY_FIELD_MAX_LENGTH = 128
MOCK_EXAM_LIST_DEFAULT_PAGE_SIZE = 20
MOCK_EXAM_LIST_MAX_PAGE_SIZE = 100

MOCK_EXAM_WEEKLY_LISTENING_COUNT = 10
MOCK_EXAM_WEEKLY_READING_COUNT = 10
MOCK_EXAM_MONTHLY_LISTENING_COUNT = 17
MOCK_EXAM_MONTHLY_READING_COUNT = 28

AI_JOB_REQUEST_ID_MAX_LENGTH = 128
AI_JOB_NOTES_MAX_LENGTH = 2000
AI_JOB_METADATA_MAX_LENGTH = 20000
AI_PROMPT_TEMPLATE_VERSION_MAX_LENGTH = 64
AI_PROVIDER_NAME_MAX_LENGTH = 64
AI_MODEL_NAME_MAX_LENGTH = 128
AI_ARTIFACT_OBJECT_KEY_MAX_LENGTH = 512
AI_JOB_LIST_DEFAULT_PAGE_SIZE = 20
AI_JOB_LIST_MAX_PAGE_SIZE = 100
AI_MOCK_EXAM_CANDIDATE_LIMIT_DEFAULT = 200
AI_MOCK_EXAM_CANDIDATE_LIMIT_MAX = 2000

SUBSCRIPTION_PLAN_CODE_MAX_LENGTH = 64
SUBSCRIPTION_DISPLAY_NAME_MAX_LENGTH = 128
SUBSCRIPTION_EXTERNAL_BILLING_REF_MAX_LENGTH = 256
SUBSCRIPTION_METADATA_MAX_LENGTH = 20000
SUBSCRIPTION_LIST_DEFAULT_PAGE_SIZE = 20
SUBSCRIPTION_LIST_MAX_PAGE_SIZE = 100
