ACCESS_TOKEN_TTL_MINUTES = 15
REFRESH_TOKEN_TTL_DAYS = 30
JWT_ALGORITHM = "HS256"
R2_UPLOAD_SIGNED_URL_TTL_SECONDS = 300
R2_DOWNLOAD_SIGNED_URL_TTL_SECONDS = 300
APP_TIMEZONE = "Asia/Seoul"
DB_TIMEZONE = "UTC"

# Phase-1 fixed policy values that can be shared by later tickets.
INVITE_CODE_TTL_SECONDS = 600
MAX_CHILDREN_PER_PARENT = 5
MAX_PARENTS_PER_CHILD = 2
INVITE_VERIFY_RATE_LIMIT_MAX_ATTEMPTS = 5
INVITE_VERIFY_RATE_LIMIT_WINDOW_SECONDS = 600
INVITE_CONSUME_RATE_LIMIT_MAX_ATTEMPTS = 5
INVITE_CONSUME_RATE_LIMIT_WINDOW_SECONDS = 600
PASSWORD_MIN_LENGTH = 8

SYNC_EVENTS_BATCH_MAX_SIZE = 100
SYNC_EVENT_SCHEMA_VERSION = 1
SYNC_DEVICE_ID_MAX_LENGTH = 128
SYNC_IDEMPOTENCY_KEY_MAX_LENGTH = 128
SYNC_EVENT_STRING_MAX_LENGTH = 128

SYNC_EVENT_TYPE_TODAY_ATTEMPT_SAVED = "TODAY_ATTEMPT_SAVED"
SYNC_EVENT_TYPE_MOCK_EXAM_ATTEMPT_SAVED = "MOCK_EXAM_ATTEMPT_SAVED"
SYNC_EVENT_TYPES = (
    SYNC_EVENT_TYPE_TODAY_ATTEMPT_SAVED,
    SYNC_EVENT_TYPE_MOCK_EXAM_ATTEMPT_SAVED,
)

WRONG_REASON_TAG_DB_VALUES = (
    "VOCAB",
    "EVIDENCE",
    "INFERENCE",
    "CARELESS",
    "TIME",
)
