ACCESS_TOKEN_TTL_MINUTES = 15
REFRESH_TOKEN_TTL_DAYS = 30
JWT_ALGORITHM = "HS256"
R2_UPLOAD_SIGNED_URL_TTL_SECONDS = 300
R2_DOWNLOAD_SIGNED_URL_TTL_SECONDS = 300
APP_TIMEZONE = "Asia/Seoul"
DB_TIMEZONE = "UTC"

# Phase-1 fixed policy values that can be shared by later tickets.
INVITE_CODE_TTL_SECONDS = 600
MAX_CHILDREN_PER_PARENT = 5
MAX_PARENTS_PER_CHILD = 2
